export default styles = {
  container: {
    padding: 10,
  },
  heading: {
    fontSize: 50,
    textAlign: 'center',
    padding: 20,
    backgroundColor: '#FFF',
    color: '#FF6A53',
    fontWeight: 'bold',
    borderBottomRightRadius: 40,
    borderBottomLeftRadius: 40,
    height: 120,
    marginBottom: 0.5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
  },
  wrapper: {
    backgroundColor: 'white',
    height: '100%',
  },
  image: {
    height: 150,
    width: 150,
    margin: 10,
  },
  productContainer: {
    alignItems: 'center',
    backgroundColor: 'white',
    padding: 10,
    margin: 20,
    shadowColor: '#FF9211',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
    borderRadius: 22,
  },
  title: {
    fontSize: 22,
    color: '#222',
    textAlign: 'left',
    fontWeight: 'bold',
  },
  price: {
    fontSize: 20,
    color: '#FF7F20',
    textAlign: 'left',
    fontWeight: '900',
  },
  ratingContainer: {
    width: '100%',
  },
  ratings: {
    fontWeight: 'bold',
    padding: 2,
    color: '#FFBA20',
    textAlign: 'left',
  },
  quantityAvailable: {
    fontWeight: 'bold',
    padding: 2,
    color: '#00B54A',
    textAlign: 'left',
  },
  category: {
    color: '#B0B0B0',
    fontWeight: 'bold',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
};
